### Passo 1 - Importar Arquivos e Bibliotecas

In [2]:
#importar bibliotecas
import pandas as pd
print(pd.__version__)

2.2.3

In [4]:
coluna = ['Tamanho', 'Idade', 'nome']
titulo_coluna = {'Nome': coluna}
tabela = pd.DataFrame(titulo_coluna)
print(tabela)

      Nome
0  Tamanho
1    Idade
2     nome

In [31]:
#importar bases de dados

emails = pd.read_excel(r'C:/Users/quel_/OneDrive/Documentos/Projeto AutomacaoIndicadores/Bases de Dados/Emails.xlsx')
lojas = pd.read_csv(r'C:/Users/quel_/OneDrive/Documentos/Projeto AutomacaoIndicadores/Bases de Dados/Lojas.csv', encoding='latin1', sep=';')
vendas = pd.read_excel(r'C:/Users/quel_/OneDrive/Documentos/Projeto AutomacaoIndicadores/Bases de Dados/Vendas.xlsx')
display(emails)
display(lojas)
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonimpressionador+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonimpressionador+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonimpressionador+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonimpressionador+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonimpressionador+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonimpressionador+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonimpressionador+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonimpressionador+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonimpressionador+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonimpressionador+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonimpressionador+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonimpressionador+arthur@gmail.com
17,Shopping Recife,Heitor,pythonimpressionador+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonimpressionador+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonimpressionador+davi@gmail.com
20,Shopping Eldorado,Theo,pythonimpressionador+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonimpressionador+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonimpressionador+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonimpressionador+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonimpressionador+benjamin@gmail.com
25,Diretoria,Diretoria,pythonimpressionador+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [32]:
#incluir nome da loja na base de vendas, no caso, ID loja tem nas duas bases
vendas = vendas.merge(lojas, on='ID Loja')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [33]:
#Criar um arquivo para cada loja
for loja in lojas['Loja']:
  print(loja)

Iguatemi Esplanada
Shopping Midway Mall
Norte Shopping
Shopping Iguatemi Fortaleza
Shopping União de Osasco
Shopping Center Interlagos
Rio Mar Recife
Salvador Shopping
Rio Mar Shopping Fortaleza
Shopping Center Leste Aricanduva
Ribeirão Shopping
Shopping Morumbi
Parque Dom Pedro Shopping
Bourbon Shopping SP
Palladium Shopping Curitiba
Passei das Águas Shopping
Center Shopping Uberlândia
Shopping Recife
Shopping Vila Velha
Shopping SP Market
Shopping Eldorado
Shopping Ibirapuera
Novo Shopping Ribeirão Preto
Iguatemi Campinas
Shopping Barra

In [34]:
#vou criar um dicionario(tabela) de cada loja para toda vez que eu quiser puxar sua tabela
dicionario_lojas = {}

for loja in lojas['Loja']:
  dicionario_lojas[loja] = vendas.loc[vendas['Loja']==loja,:]

  #testando lojas
display(dicionario_lojas['Rio Mar Recife'])
display(dicionario_lojas['Shopping Vila Velha'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
62,46,2019-01-02,7,Camisa,1,100,100,Rio Mar Recife
63,46,2019-01-02,7,Calça Liso,2,190,380,Rio Mar Recife
64,46,2019-01-02,7,Cinto,1,200,200,Rio Mar Recife
113,87,2019-01-02,7,Camisa Estampa,1,113,113,Rio Mar Recife
142,109,2019-01-02,7,Camisa Gola V Listrado,3,116,348,Rio Mar Recife
...,...,...,...,...,...,...,...,...
100858,69905,2019-12-25,7,Mochila Listrado,2,275,550,Rio Mar Recife
100859,69905,2019-12-25,7,Camisa Xadrez,3,105,315,Rio Mar Recife
100860,69905,2019-12-25,7,Tênis Liso,3,266,798,Rio Mar Recife
100929,69954,2019-12-25,7,Chinelo,3,60,180,Rio Mar Recife
100930,69954,2019-12-25,7,Casaco Listrado,3,269,807,Rio Mar Recife

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
40,32,2019-01-02,19,Polo Liso,1,137,137,Shopping Vila Velha
41,32,2019-01-02,19,Polo Listrado,2,149,298,Shopping Vila Velha
49,38,2019-01-02,19,Meia Xadrez,3,41,123,Shopping Vila Velha
50,38,2019-01-02,19,Relógio,1,200,200,Shopping Vila Velha
107,82,2019-01-02,19,Meia Listrado,1,37,37,Shopping Vila Velha
...,...,...,...,...,...,...,...,...
100726,69801,2019-12-25,19,Bermuda,3,150,450,Shopping Vila Velha
100795,69859,2019-12-25,19,Meia Liso,2,38,76,Shopping Vila Velha
100960,69970,2019-12-26,19,Casaco Linho,2,299,598,Shopping Vila Velha
100965,69974,2019-12-26,19,Meia Listrado,3,37,111,Shopping Vila Velha
100984,69985,2019-12-26,19,Pulseira Linho,2,114,228,Shopping Vila Velha

In [35]:
#codigo pronto para toda vez que entrar um dia novo, ele conseguir calcular o indicador desse dia novo
#então vou olhar a coluna de data e pegar a maior data, pq a maior data é a mais recente 

#dia do indicador: ultima data da coluna data
dia_indicador = vendas['Data'].max()
print(dia_indicador)
print(dia_indicador.day)
print(dia_indicador.month)
print(dia_indicador.year)

#ou ainda
print('{}/{}/{}'.format(dia_indicador.day,dia_indicador.month,dia_indicador.year))

2019-12-26 00:00:00
26
12
2019
26/12/2019

### Passo 3 - Salvar a planilha na pasta de backup

In [39]:
#identificar se a pasta ja existe. Para quando surgir loja nova e já rodar o codigo automaticamente, ja adicionar a pasta automatic 
import pathlib

caminho_backup = pathlib.Path(r'C:/Users/quel_/OneDrive/Documentos/Projeto AutomacaoIndicadores/Backup Arquivos Lojas')

#iter dir pega todos os arquivos e pastas que estao dentro do diretorio
arquivos_pasta_backup = caminho_backup.iterdir()

#vai criar um lista com o nome de todas as pastas
# lista_nomes_backup = []
# for arquivo in arquivos_pasta_backup:
#   lista_nomes_backup.append(arquivo.name)

#usando list compression
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]
print(lista_nomes_backup)


#mas caso a loja não exista, criarei a pasta
for loja in dicionario_lojas:
  if loja not in lista_nomes_backup:
    nova_pasta = caminho_backup / loja
    nova_pasta.mkdir() #cria de fato um novo caminho/pasta

  #nome do arquivo: mes_dia_ano
  nome_arquivo = '{}_{}_{}.xlsx'.format(dia_indicador.month, dia_indicador.day,loja)
  print(nome_arquivo)
  #local_arquivo = "C:/Users.../mes_dia_nomeLoja.xlsx"
  local_arquivo = caminho_backup / loja / nome_arquivo
  
dicionario_lojas[loja].to_excel(local_arquivo)

[]
12_26_Iguatemi Esplanada.xlsx
12_26_Shopping Midway Mall.xlsx
12_26_Norte Shopping.xlsx
12_26_Shopping Iguatemi Fortaleza.xlsx
12_26_Shopping União de Osasco.xlsx
12_26_Shopping Center Interlagos.xlsx
12_26_Rio Mar Recife.xlsx
12_26_Salvador Shopping.xlsx
12_26_Rio Mar Shopping Fortaleza.xlsx
12_26_Shopping Center Leste Aricanduva.xlsx
12_26_Ribeirão Shopping.xlsx
12_26_Shopping Morumbi.xlsx
12_26_Parque Dom Pedro Shopping.xlsx
12_26_Bourbon Shopping SP.xlsx
12_26_Palladium Shopping Curitiba.xlsx
12_26_Passei das Águas Shopping.xlsx
12_26_Center Shopping Uberlândia.xlsx
12_26_Shopping Recife.xlsx
12_26_Shopping Vila Velha.xlsx
12_26_Shopping SP Market.xlsx
12_26_Shopping Eldorado.xlsx
12_26_Shopping Ibirapuera.xlsx
12_26_Novo Shopping Ribeirão Preto.xlsx
12_26_Iguatemi Campinas.xlsx
12_26_Shopping Barra.xlsx

In [37]:
#agora preciso transformar o nome da pasta em um arquivo excel/dataframe

dicionario_lojas[loja].to_excel(local_arquivo)

### Passo 4 - Calcular o indicador para 1 loja

### Passo 5 - Enviar por e-mail para o gerente

### Passo 6 - Automatizar todas as lojas

### Passo 7 - Criar ranking para diretoria

### Passo 8 - Enviar e-mail para diretoria